### ISSUE TITLE
Compartilha a idéia

### ISSUE THREAD

**Issue by gabrielsimas** [maiconheck/keepmoney#1]
Maicon.
Compartilha a idéia, que eu te ajudo a desenvolver.
Pode começar com algo simples. Tenho tb algumas idéias no meu GitHub sobre questões do dia a dia.

**Comment by maiconheck** [comment]
Olá @gabrielsimas, obrigado pelo interesse, e desculpe a demora em responder!

Eu vou melhorar o `README.md` para que a proposta fique mais clara, adicionando uma seção para contribuição assim que eu terminar uma refatoração que estou fazendo nesse, e em outros repositórios relacionados.

Qualquer ideia que quiser trocar, pode também me mandar DM aqui [linkedin.com/in/maiconheck/](https://www.linkedin.com/in/maiconheck/)

Abraço
